In [4]:
%matplotlib inline
import math
import numpy as np
from matplotlib import pyplot as plt

# Linear Equation

A linear equation is an equation that describes a straight line when plotted on a graph e.g. $x+4y+5z = 5$. There is no terms like $x^2$ or $xy$.

For example the system of linear equations:
$$
\begin{align*}
x_1 + x_2 + x_3 &= 6 \\
2x_1 + 3x_2 + x_3 &= 11 \\
-3x_1 + 4x_2 - 2x_3 &= -1
\end{align*}
$$

In general, a system of linear equations can be written in matrix form as:

$$
A x = B
$$

where $A = \begin{bmatrix}
1 & 1 & 1 \\
2 & 3 & 1 \\
-3 & 4 & -2
\end{bmatrix}$, $x = \begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}$ , and $B = \begin{bmatrix}
6 \\
11 \\
-1
\end{bmatrix}$. Our goal is to find $x$.



## Solving using Gaussian Elimination:

Gaussian elimination is a method for solving systems of linear equations. It consists of two steps:

1. **Forward elimination:** Transform the matrix $A$ into an upper triangular matrix.
2. **Back substitution:** Solve for the unknowns starting from the last equation.



show how to do step-by-step for forward elimination the example above
To perform forward elimination step-by-step for the example system:

1. **Write the augmented matrix:**

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6 \\
2 & 3 & 1 & 11 \\
-3 & 4 & -2 & -1
\end{array}
\right]
$$

2. **Eliminate $x_1$ from rows 2 and 3:**

- Row 2: $R_2 - 2R_1$
- Row 3: $R_3 + 3R_1$

Result:

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6 \\
0 & 1 & -1 & -1 \\
0 & 7 & 1 & 17
\end{array}
\right]
$$

3. **Eliminate $x_2$ from row 3:**

- Row 3: $R_3 - 7R_2$

Result:

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6 \\
0 & 1 & -1 & -1 \\
0 & 0 & 8 & 24
\end{array}
\right]
$$

Now the matrix is upper triangular and ready for back substitution.


step-by-step back substitution:

1. Start with the upper triangular matrix from forward elimination:

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6 \\
0 & 1 & -1 & -1 \\
0 & 0 & 8 & 24
\end{array}
\right]
$$

2. **Solve for $x_3$ using the last row:**

$$
8x_3 = 24 \implies x_3 = 3
$$

3. **Substitute $x_3$ into the second row to solve for $x_2$:**

$$
x_2 - x_3 = -1 \implies x_2 - 3 = -1 \implies x_2 = 2
$$

4. **Substitute $x_2$ and $x_3$ into the first row to solve for $x_1$:**

$$
x_1 + x_2 + x_3 = 6 \implies x_1 + 2 + 3 = 6 \implies x_1 = 1
$$

**Final solution:**

$$
x_1 = 1,\quad x_2 = 2,\quad x_3 = 3
$$

In [5]:
'''
write down your code here
A = ...
B = ...
def forward_elim(A, B):
    ...
    return A, B
def back_sub(A, B):
    ...
    return A, B
'''

A = np.array([[1., 1., 1.],
              [2., 3., 1.],
              [-3., 4., -2.]])

B = np.array([6., 11., -1.])

def forward_elim(A, B):
    a = A.copy()
    b = B.copy()
    n = len(b)
    for pivot in range(n-1):
        for target in range(pivot+1, n):
            if a[target,pivot] == 0: 
                continue
            coef = a[target,pivot]/a[pivot,pivot]
            a[target] = a[target] - coef * a[pivot]
            b[target] = b[target] - coef * b[pivot]
    return a, b

def back_sub(A, B):
    a = A.copy()
    b = B.copy()
    n = len(b)
    
    for i in range(n - 1, -1, -1):

        # This makes the pivot element equal to 1.
        pivot_val = a[i, i]
        a[i] = a[i] / pivot_val
        b[i] = b[i] / pivot_val

        # Eliminate the elements above the pivot:
        for j in range(i - 1, -1, -1):
            factor = a[j, i]
        
            # make the element a[j, i] zero.
            a[j] = a[j] - factor * a[i]
            b[j] = b[j] - factor * b[i]

    return a, b # Return the identity matrix and the solution vector

def gauss_elim(A, B):
    A, B = forward_elim(A, B)
    A, B = back_sub(A, B)
    return A, B

A, B = gauss_elim(A, B)
print(A)
print(B)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 2. 3.]


In [6]:
#test your function with the following code

np.random.seed(100)
A = np.random.rand(100,100)
x = np.random.rand(100)
B = A @ x
_, sol = gauss_elim(A, B)
print("solution error:", x - sol)

solution error: [-1.52711177e-12  1.94511074e-13 -6.73794354e-13 -1.42275081e-13
  5.10702591e-15  7.65720820e-13  7.53730411e-13  8.53594972e-13
 -1.37977130e-12  4.54775106e-13 -3.14193116e-14  4.27241575e-13
 -3.16413562e-13 -2.21933583e-13 -1.04971587e-13 -2.38198350e-13
 -1.27675648e-13  1.32294176e-12  5.79647441e-13 -6.59805544e-13
 -1.11466392e-13 -4.18665103e-13  6.61193322e-13 -1.29118938e-12
 -2.00839345e-13 -7.58133140e-13 -1.45439216e-13 -5.80424597e-13
  2.11275442e-13 -9.99200722e-14 -1.04100062e-12  5.77426995e-13
  1.13359322e-12  1.44007029e-12 -7.58726415e-13 -1.01341158e-12
 -1.81343829e-12  7.92588217e-13  8.28226376e-13 -3.50330875e-13
  1.71751502e-13 -1.00472408e-12 -8.50097770e-13  2.89768209e-14
  4.27102798e-13  4.60409488e-13  1.06581410e-13  2.70561351e-13
  9.09217146e-13  1.02373665e-12  3.47777362e-13 -6.02795591e-13
  1.59272595e-12 -4.57911487e-13 -6.22280005e-14  5.50323676e-13
 -7.61724017e-13 -1.23515087e-12 -6.32743857e-13 -5.31796829e-14
 -2.83884

In practice, you can use a functon `np.linalg.solve`

In [8]:
sol2 = np.linalg.solve(A, B)
print("solution error:", x - sol2)

solution error: [-1.04249942e-13 -4.77395901e-15 -1.83186799e-14 -3.89965837e-14
 -1.22124533e-14  3.27515792e-14 -4.49640325e-15  7.86037901e-14
 -7.55923102e-14  2.71171974e-14  3.33066907e-16  1.21014310e-14
 -2.00950367e-14  1.16573418e-14 -1.17961196e-14 -3.38062911e-14
 -2.02615702e-14  8.55981952e-14  5.69544412e-14 -5.34017275e-14
  3.14193116e-14 -4.13002965e-14  4.31321645e-14 -9.54791801e-14
 -2.52575738e-14 -3.65185313e-14 -2.42861287e-14 -5.35682609e-14
  1.23234756e-14  9.43689571e-15 -7.48290319e-14  4.74065232e-14
  6.97220059e-14  1.24386612e-13 -5.07371922e-14 -5.89528426e-14
 -1.02251541e-13  4.37427872e-14  3.82471832e-14 -1.04360964e-14
  1.69864123e-14 -6.90697499e-14 -3.95239397e-14  2.08721929e-14
  3.45279361e-14  4.72955008e-14  1.49880108e-14  2.73114864e-14
  6.66133815e-14  5.60662627e-14 -1.20459198e-14 -2.35922393e-14
  9.35918010e-14 -2.87547763e-14 -1.73749903e-14  4.05508960e-14
 -4.87387908e-14 -1.10078613e-13 -5.98687766e-14  2.16493490e-15
  5.55111

The time complexity for solving a system of $n$ linear equations  ($A$ is $n \times n$ matrix) using Gaussian elimination is $O(n^3)$.

The best-known asymptotic running time is $O(n^\omega)$ (same running time as two n×n matrix multiplication).

The exponent $\omega$ determines how fast we can multiply matrices and solve linear systems. Every tiny improvement means huge speedups for scientific computing, machine learning, and physics simulations! Reducing $\omega$ is a major achievement in theoretical computer science.


| Year | Bound on ω | Authors |
|------|------------|-----------------------------------------------|
| 1969 | 2.8074     | Strassen                                   |
| 1978 | 2.796      | Pan                                        |
| 1979 | 2.780      | Bini, Capovani, Romani                     |
| 1981 | 2.522      | Schönhage                                  |
| 1981 | 2.517      | Romani                                     |
| 1981 | 2.496      | Coppersmith, Winograd                      |
| 1986 | 2.479      | Strassen                                   |
| 1990 | 2.3755     | Coppersmith, Winograd                      |
| 2010 | 2.3737     | Stothers                                   |
| 2012 | 2.3729     | Williams                                   |
| 2014 | 2.3728639  | Le Gall                                    |
| 2020 | 2.3728596  | Alman, Williams                            |
| 2022 | 2.371866   | Duan, Wu, Zhou                             |
| 2024 | 2.371552   | Williams, Xu, Xu, and Zhou                 |
| 2024 | 2.371339   | Alman, Duan, Williams, Xu, Xu, and Zhou    |

