## Solving ordinary differential equations using Numpy and Scipy

### 1.2.1 Second order ordinary differential equation in One dimention

From: http://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html

Integrating a set of ordinary differential equations (ODEs) given initial conditions is another useful example. The function odeint is available in SciPy for integrating a first-order vector differential equation:

$$\frac{d\mathbf{y}}{dt}=\mathbf{f}\left(\mathbf{y},t\right)$$

given initial conditions $\mathbf{y}\left(0\right)=y_{0}$ where $y$ is a length $N$ vector and $f$ is a mapping from $\mathcal{R}^{N}$ to $\mathcal{R}^{N}$. A higher-order ordinary differential equation can always be reduced to a differential equation of this type by introducing intermediate derivatives into the $y$ vector.

For example suppose it is desired to find the solution to the following second-order differential equation:

$$\frac{d^{2}w}{dz^{2}}-zw(z)=0$$

with initial conditions $w\left(0\right)=\frac{1}{\sqrt[3]{3^{2}}\Gamma\left(\frac{2}{3}\right)}$ and $\left.\frac{dw}{dz}\right|_{z=0}=-\frac{1}{\sqrt[3]{3}\Gamma\left(\frac{1}{3}\right)}$. It is known that the solution to this differential equation with these boundary conditions is the Airy function

$$w=\textrm{Ai}\left(z\right)$$

which gives a means to check the integrator using special.airy.

First, convert this ODE into standard form by setting $\mathbf{y}=\left[\frac{dw}{dz},w\right]$ and $t = z$. Thus, the differential equation becomes

$$\begin{split}\frac{d\mathbf{y}}{dt}=\left[\begin{array}{c} ty_{1}\\ y_{0}\end{array}\right]=\left[\begin{array}{cc} 0 & t\\ 1 & 0\end{array}\right]\left[\begin{array}{c} y_{0}\\ y_{1}\end{array}\right]=\left[\begin{array}{cc} 0 & t\\ 1 & 0\end{array}\right]\mathbf{y}.\end{split}$$

In other words,

$$\mathbf{f}\left(\mathbf{y},t\right)=\mathbf{A}\left(t\right)\mathbf{y}$$

As an interesting reminder, if $\mathbf{A}\left(t\right)$ commutes with $\int_{0}^{t}\mathbf{A}\left(\tau\right)\, d\tau$ under matrix multiplication, then this linear differential equation has an exact solution using the matrix exponential:

$$\mathbf{y}\left(t\right)=\exp\left(\int_{0}^{t}\mathbf{A}\left(\tau\right)d\tau\right)\mathbf{y}\left(0\right)$$

However, in this case, $\mathbf{A}(t)$ and its integral do not commute.

There are many optional inputs and outputs available when using odeint which can help tune the solver. These additional inputs and outputs are not needed much of the time, however, and the three required input arguments and the output solution suffice. The required inputs are the function defining the derivative, fprime, the initial conditions vector, $y0$, and the time points to obtain a solution, $t$, (with the initial value point as the first element of this sequence). The output to odeint is a matrix where each row contains the solution vector at each requested time point (thus, the initial conditions are given in the first output row).

The following example illustrates the use of odeint including the usage of the Dfun option which allows the user to specify a gradient (with respect to $y$) of the function, $\mathbf{f}\left(\mathbf{y},t\right)$.

In [1]:
from scipy.integrate import odeint
from scipy.special import gamma, airy
import numpy as np

# calculate initial conditions, y0
y1_0 = 1.0 / 3**(2.0/3.0) / gamma(2.0/3.0)
y0_0 = -1.0 / 3**(1.0/3.0) / gamma(1.0/3.0)
y0 = [y0_0, y1_0]

# define vector f(y,t)
def func(y, t):
    return [t*y[1],y[0]]

# define gradient matrix
def gradient(y, t):
    return [[0,t], [1,0]]

x = np.arange(0, 4.0, 0.01)
t = x
ychk = airy(x)[0]

y = odeint(func, y0, t)
y2 = odeint(func, y0, t, Dfun=gradient)

print(ychk[:36:6])

print(y[:36:6,1])

print(y2[:36:6,1])

[0.35502805 0.33951139 0.32406751 0.30876307 0.29365818 0.27880648]
[0.35502805 0.33951138 0.32406749 0.30876306 0.29365817 0.27880648]
[0.35502805 0.33951138 0.32406749 0.30876306 0.29365817 0.27880648]


---
**Exercise 1:** Solve

$$\ddot y =  - 4y$$

where $y(0) = 1$ and $\dot y(0) = 0$, on the interval $0 \le t \le 2 \pi$.

First, **write down** the vector $\mathbf{y}$ and the matrix equation for $\frac{d\mathbf{y}}{dt}$.

Then, **write code** to solve the problem.

Finally, **plot graph** of the solution in the interval.

*--->Replace this with $\mathbf{y}$ and  $\frac{d\mathbf{y}}{dt}$*

In [14]:
# write codes

---
**Exercise 2:** Large amplitude pendulum

A motion of a pedulum is given exactly (without approximation) by:

$$\ddot \theta =  - \frac{g}{l} sin \theta$$

For simplicity, choose $g = 10\;m/s^2$ and $l = 1\;m$.

First **write down** the vector $\mathbf{\theta}$ and the matrix equation for $\frac{d\mathbf{\theta}}{dt}$. 

**Solve** the problem for the amplitude of oscillation equals to $\frac {\pi}{2}$.

Then, **plot graph** between the angle $\theta$ as a function of time.

What is difference between the periods of the large amplitude oscillation and of the SHM pendulum?

*--->Replace this with $\mathbf{\theta}$ and  $\frac{d\mathbf{\theta}}{dt}$*

In [15]:
# write codes

---
### 1.2.2 Second order ordinary differential equation in Two dimentions

At this point, it should be obvious how to solve the two dimentional problem, shouldn't it?

We can extend the one dimentional problem to two dimentional problem by modifying the vector $\mathbf {y}$.

Let's consider a position vector $\vec{r}$.

$$\frac{d\vec{r}}{dt} = \vec{v}$$

which can be written in term of components as

$$\frac{dx}{dt} = v_x$$

$$\frac{dy}{dt} = v_y$$

So vector $\mathbf {y}$ can be modified to

$$\mathbf {y} = \begin{pmatrix}
x\\
v_x\\
y\\
v_y
\end{pmatrix}$$


So the equation is now in the form of

$$\frac{d\mathbf{y}}{dt}=\mathbf{f}\left(\mathbf{y},t\right)$$

which can be solve with scipy solver.

---
**Excercise 3:** Projectile with air resistance

Consider a projectile problem under gravity $\mathbf g$ and air resistance that is directly proportional to its velocity, i.e. $c \mathbf v$. The equation of motion is governed by:

$$\frac{d\mathbf{v}}{dt} = \mathbf{g} - c \mathbf{v}$$

given that $g = 9.8\;m/s^2$ and $c = 0.1\;s^{-1}$. Subjected to the initial conditions:

$$v_x(0) = 20 \; m/s \; \text{and}\;  v_y(0) = 0$$
$$x(0) = 0, y(0) = 0$$

First **write down** the vector $\mathbf{y}$ and the matrix equation for $\frac{d\mathbf{y}}{dt}$.

**Solve** the problem for $x$ and $y$ on the time interval $0 \le t \le 10\; s$.

Then, **plot graph** of both components as function of time.
